// AUTH ACTIONS
export const AUTH_CHANGED = "AUTH_CHANGED";
export const EMAIL_AUTH_INIT = "EMAIL_AUTH_INIT";
export const EMAIL_AUTH_FAIL = "EMAIL_AUTH_FAIL";
export const EMAIL_REGISTER_INIT = "EMAIL_REGISTER_INIT";
export const EMAIL_REGISTER_SUCCESS = "EMAIL_REGISTER_SUCCESS";
export const EMAIL_REGISTER_FAIL = "EMAIL_REGISTER_FAIL";
export const GET_USER_DATA_INIT = "GET_USER_DATA_INIT";
export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const GET_USER_DATA_FAIL = "GET_USER_DATA_FAIL";
export const SET_USER_DATA_INIT = "SET_USER_DATA_INIT";
export const SET_USER_DATA_SUCCESS = "SET_USER_DATA_SUCCESS";
export const SET_USER_DATA_FAIL = "SET_USER_DATA_FAIL";
export const LOGOUT = "LOGOUT";
