// AUTH ACTIONS
export const AUTH_CHANGED = "AUTH_CHANGED";
export const EMAIL_AUTH_INIT = "EMAIL_AUTH_INIT";
export const EMAIL_AUTH_FAIL = "EMAIL_AUTH_FAIL";
export const EMAIL_REGISTER_INIT = "EMAIL_REGISTER_INIT";
export const EMAIL_REGISTER_SUCCESS = "EMAIL_REGISTER_SUCCESS";
export const EMAIL_REGISTER_FAIL = "EMAIL_REGISTER_FAIL";
export const GET_USER_DATA_INIT = "GET_USER_DATA_INIT";
export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const GET_USER_DATA_FAIL = "GET_USER_DATA_FAIL";
export const SET_USER_DATA_INIT = "SET_USER_DATA_INIT";
export const SET_USER_DATA_SUCCESS = "SET_USER_DATA_SUCCESS";
export const SET_USER_DATA_FAIL = "SET_USER_DATA_FAIL";
export const SET_IMG_INIT = "SET_IMG_INIT";
export const SET_IMG_SUCCESS = "SET_IMG_SUCCESS";
export const SET_IMG_FAIL = "SET_IMG_FAIL";
export const SET_ABOUT_INIT = "SET_ABOUT_INIT";
export const SET_ABOUT_SUCCESS = "SET_ABOUT_SUCCESS";
export const SET_ABOUT_FAIL = "SET_ABOUT_FAIL";
export const LOGOUT = "LOGOUT";

// CONTACT ACTIONS
export const GET_CONTACTS_INIT = "GET_CONTACTS_INIT";
export const GET_CONTACTS_FAIL = "GET_CONTACTS_FAIL";
export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS";
export const ADD_CONTACT_INIT = "ADD_CONTACTS_INIT";
export const ADD_CONTACT_FAIL = "ADD_CONTACTS_FAIL";
export const ADD_CONTACT_SUCCESS = "ADD_CONTACTS_SUCCESS";
export const SELECT_CONTACT = "SELECT_CONTACT";
export const CLEAR_SELECTED_CONTACT = "CLEAR_SELECTED_CONTACT";
export const SEND_MESSAGE_INIT = "SEND_MESSAGES_INIT";
export const SEND_MESSAGE_FAIL = "SEND_MESSAGES_FAIL";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGES_SUCCESS";
export const UPDATE_MESSAGE_INIT = "UPDATE_MESSAGE_INIT";
export const UPDATE_MESSAGE_FAIL = "UPDATE_MESSAGE_FAIL";
export const UPDATE_MESSAGE_SUCCESS = "UPDATE_MESSAGE_SUCCESS";
export const GET_PREVIOUS_MESSAGES_INIT = "GET_PREVIOUS_MESSAGES_INIT";
export const GET_PREVIOUS_MESSAGES_FAIL = "GET_PREVIOUS_MESSAGES_FAIL";
export const GET_PREVIOUS_MESSAGES_SUCCESS = "GET_PREVIOUS_MESSAGES_SUCCESS";
export const RESET_NEW_MESSAGES_COUNT = "RESET_NEW_MESSAGES_COUNT";
export const CLEAR_CONTACTS = "CLEAR_CONTACTS";

// UI ACTIONS
export const SET_IS_DARK_MODE_ENABLED = "SET_IS_DARK_MODE_ENABLED";
export const SET_IS_SIDE_DRAWER_SHOWN = "SET_IS_SIDE_DRAWER_SHOWN";
