// AUTH ACTIONS
export const AUTH_CHANGED = "AUTH_CHANGED";
export const EMAIL_AUTH_INIT = "EMAIL_AUTH_INIT";
export const EMAIL_AUTH_FAIL = "EMAIL_AUTH_FAIL";
export const EMAIL_REGISTER_INIT = "EMAIL_REGISTER_INIT";
export const EMAIL_REGISTER_SUCCESS = "EMAIL_REGISTER_SUCCESS";
export const EMAIL_REGISTER_FAIL = "EMAIL_REGISTER_FAIL";
export const LOGOUT = "LOGOUT";
